version: '3.10'

services:
  api:
    build: .
    image: upload-videos
    container_name: upload-videos-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1