apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${REPO_NAME}
  template:
    metadata:
      labels:
        app: ${REPO_NAME}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app  # Nome do label do node
      containers:
      - name: ${REPO_NAME}
        image: ${ECR_REGISTRY}/${REPO_NAME}:latest
        ports:
        - containerPort: 8000
        env:
          - name: ACCESS_KEY
            value: ${AWS_ACCESS_KEY_ID}
          - name: SECRET_KEY
            value: ${AWS_SECRET_ACCESS_KEY}
          - name: QUEUE_URL
            value: ${QUEUE_URL}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"